name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 拉取代码 - Checkout repository
        uses: actions/checkout@v2

      - name: 设置 Node - Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 设置 Rust - Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - name: 安装依赖（Ubuntu） - Install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: 安装 APP 依赖并打包 Web 资源 - Install app dependencies and build web
        run: yarn && yarn build

      - name: 打包 APP - Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "根据系统版本下载。 - See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
