name: MinIO Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 处理 Mac 环境
        run: |
          brew install minio/stable/mc
          mc --help
      - name: 设置 OSS 信息
        run: |
          mc alias set deploy $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4
        env:
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      - name: 上传文件
        run: |
          mc mirror --overwrite $SOURCE_DIR "deploy/$BUCKET$TARGET_DIR"
        env:
          BUCKET: "app"
          SOURCE_DIR: "public"
          TARGET_DIR: "/iHost"
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
